const { PrismaClient } = require('@prisma/client');
const { seedCompliance } = require('./compliance-seed');

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding localization data...');

  // Languages
  const [en, ar, ka] = await Promise.all([
    prisma.language.upsert({
      where: { code: 'en' },
      create: { code: 'en', name: 'English', nativeName: 'English', isActive: true },
      update: {},
    }),
    prisma.language.upsert({
      where: { code: 'ar' },
      create: { code: 'ar', name: 'Arabic', nativeName: 'العربية', isActive: true },
      update: {},
    }),
    prisma.language.upsert({
      where: { code: 'ka' },
      create: { code: 'ka', name: 'Georgian', nativeName: 'ქართული', isActive: true },
      update: {},
    }),
  ]);
  console.log('Languages seeded: English, Arabic, Georgian');

  // Currencies
  const [, aed, sar, qar, gel] = await Promise.all([
    prisma.currency.upsert({
      where: { code: 'USD' },
      create: { code: 'USD', name: 'US Dollar', symbol: '$', isActive: true },
      update: {},
    }),
    prisma.currency.upsert({
      where: { code: 'AED' },
      create: { code: 'AED', name: 'UAE Dirham', symbol: 'AED', isActive: true },
      update: {},
    }),
    prisma.currency.upsert({
      where: { code: 'SAR' },
      create: { code: 'SAR', name: 'Saudi Riyal', symbol: 'SAR', isActive: true },
      update: {},
    }),
    prisma.currency.upsert({
      where: { code: 'QAR' },
      create: { code: 'QAR', name: 'Qatari Riyal', symbol: 'QAR', isActive: true },
      update: {},
    }),
    prisma.currency.upsert({
      where: { code: 'GEL' },
      create: { code: 'GEL', name: 'Georgian Lari', symbol: 'GEL', isActive: true },
      update: {},
    }),
  ]);
  console.log('Currencies seeded: USD, AED, SAR, QAR, GEL');

  // Country profiles
  await Promise.all([
    prisma.countryProfile.upsert({
      where: { countryCode: 'AE' },
      create: {
        countryCode: 'AE',
        countryName: 'United Arab Emirates',
        defaultCurrencyId: aed.id,
        defaultLanguageId: ar.id,
        dateFormat: 'DD/MM/YYYY',
        timezone: 'Asia/Dubai',
        taxLabel: 'VAT',
        taxNumberLabel: 'TRN',
        defaultTaxRate: 5,
        isActive: true,
      },
      update: {},
    }),
    prisma.countryProfile.upsert({
      where: { countryCode: 'SA' },
      create: {
        countryCode: 'SA',
        countryName: 'Saudi Arabia',
        defaultCurrencyId: sar.id,
        defaultLanguageId: ar.id,
        dateFormat: 'DD/MM/YYYY',
        timezone: 'Asia/Riyadh',
        taxLabel: 'VAT',
        taxNumberLabel: 'VAT Number',
        defaultTaxRate: 15,
        isActive: true,
      },
      update: {},
    }),
    prisma.countryProfile.upsert({
      where: { countryCode: 'QA' },
      create: {
        countryCode: 'QA',
        countryName: 'Qatar',
        defaultCurrencyId: qar.id,
        defaultLanguageId: ar.id,
        dateFormat: 'DD/MM/YYYY',
        timezone: 'Asia/Qatar',
        taxLabel: 'Tax',
        taxNumberLabel: 'Tax Number',
        defaultTaxRate: 0,
        isActive: true,
      },
      update: {},
    }),
    prisma.countryProfile.upsert({
      where: { countryCode: 'GE' },
      create: {
        countryCode: 'GE',
        countryName: 'Georgia',
        defaultCurrencyId: gel.id,
        defaultLanguageId: ka.id,
        dateFormat: 'DD/MM/YYYY',
        timezone: 'Asia/Tbilisi',
        taxLabel: 'VAT',
        taxNumberLabel: 'TIN',
        defaultTaxRate: 18,
        isActive: true,
      },
      update: {},
    }),
  ]);
  console.log('Country profiles seeded: UAE, Saudi Arabia, Qatar, Georgia');

  // Plans — canonical feature set: same label/category/order across all plans, only `included` varies
  const MASTER_FEATURES = [
    { category: 'Invoicing',              label: 'Create & send invoices' },
    { category: 'Invoicing',              label: 'PDF invoice generation' },
    { category: 'Invoicing',              label: 'Customer management' },
    { category: 'Invoicing',              label: 'Invoice status tracking' },
    { category: 'Invoicing',              label: 'Recurring invoices' },
    { category: 'Invoicing',              label: 'Unlimited invoices' },
    { category: 'Payments & Receivables', label: 'Manual payment recording' },
    { category: 'Payments & Receivables', label: 'Payment allocation to invoices' },
    { category: 'Payments & Receivables', label: 'Payment history & reports' },
    { category: 'Payments & Receivables', label: 'Accounts receivable dashboard' },
    { category: 'Payments & Receivables', label: 'Aging analysis' },
    { category: 'Payments & Receivables', label: 'Collections management' },
    { category: 'Expenses',               label: 'Expense tracking' },
    { category: 'Expenses',               label: 'Expense categories & suppliers' },
    { category: 'Expenses',               label: 'Receipt & file attachments' },
    { category: 'Expenses',               label: 'Expense export (CSV)' },
    { category: 'Expenses',               label: 'Expense approval workflows' },
    { category: 'Expenses',               label: 'Reimbursement management' },
    { category: 'Expenses',               label: 'Budget tracking & alerts' },
    { category: 'Expenses',               label: 'Recurring expenses & anomaly detection' },
    { category: 'AI Assistant',           label: 'Basic AI assistant' },
    { category: 'AI Assistant',           label: 'Workspace AI copilot' },
    { category: 'AI Assistant',           label: 'AI expense categorization' },
    { category: 'AI Assistant',           label: 'AI vendor intelligence & duplicate detection' },
    { category: 'AI Assistant',           label: 'AI document generation' },
    { category: 'AI Assistant',           label: 'AI compliance assistant' },
    { category: 'AI Assistant',           label: 'AI action framework with governance' },
    { category: 'AI Assistant',           label: 'Natural language queries across modules' },
    { category: 'Compliance',             label: 'Compliance calendar' },
    { category: 'Compliance',             label: 'Compliance templates & tracking' },
    { category: 'Compliance',             label: 'Submission tracking & activity logs' },
    { category: 'Compliance',             label: 'Compliance reminders & escalations' },
    { category: 'Compliance',             label: 'Compliance intelligence & health scoring' },
    { category: 'Compliance',             label: 'Risk detection & recommendations' },
    { category: 'Compliance',             label: 'AI compliance actions & automation' },
    { category: 'Documents',              label: 'Document generation' },
    { category: 'Documents',              label: 'Document templates & branding profiles' },
    { category: 'Documents',              label: 'PDF / DOCX / HTML export' },
    { category: 'Documents',              label: 'Document version history' },
    { category: 'Documents',              label: 'AI tone, quality & content enhancement' },
    { category: 'Reports & Analytics',    label: 'Basic dashboard' },
    { category: 'Reports & Analytics',    label: 'Standard reports & CSV export' },
    { category: 'Reports & Analytics',    label: 'Scheduled & saved reports' },
    { category: 'Reports & Analytics',    label: 'Advanced analytics & forecasting' },
    { category: 'Reports & Analytics',    label: 'Business health score & risk alerts' },
    { category: 'Reports & Analytics',    label: 'AI-powered insights & summaries' },
    { category: 'Platform',               label: 'Email notifications' },
    { category: 'Platform',               label: 'In-app notifications' },
    { category: 'Platform',               label: 'SMS notifications' },
    { category: 'Platform',               label: 'Role-based permissions (RBAC)' },
    { category: 'Platform',               label: 'Audit logs & activity history' },
    { category: 'Platform',               label: 'Priority support' },
    { category: 'Platform',               label: 'API access & integrations' },
    { category: 'Platform',               label: 'Custom branding & white-label' },
  ];

  const PLAN_INCLUSIONS = {
    free: new Set([
      'Create & send invoices',
      'PDF invoice generation',
      'Customer management',
      'Invoice status tracking',
      'Manual payment recording',
      'Basic AI assistant',
      'Basic dashboard',
      'Email notifications',
    ]),
    starter: new Set([
      'Create & send invoices',
      'PDF invoice generation',
      'Customer management',
      'Invoice status tracking',
      'Recurring invoices',
      'Manual payment recording',
      'Payment allocation to invoices',
      'Payment history & reports',
      'Accounts receivable dashboard',
      'Aging analysis',
      'Expense tracking',
      'Expense categories & suppliers',
      'Receipt & file attachments',
      'Expense export (CSV)',
      'Basic AI assistant',
      'Compliance calendar',
      'Document generation',
      'Basic dashboard',
      'Standard reports & CSV export',
      'Email notifications',
      'In-app notifications',
      'Role-based permissions (RBAC)',
    ]),
    professional: new Set([
      'Create & send invoices',
      'PDF invoice generation',
      'Customer management',
      'Invoice status tracking',
      'Recurring invoices',
      'Manual payment recording',
      'Payment allocation to invoices',
      'Payment history & reports',
      'Accounts receivable dashboard',
      'Aging analysis',
      'Collections management',
      'Expense tracking',
      'Expense categories & suppliers',
      'Receipt & file attachments',
      'Expense export (CSV)',
      'Expense approval workflows',
      'Reimbursement management',
      'Budget tracking & alerts',
      'Recurring expenses & anomaly detection',
      'Basic AI assistant',
      'Workspace AI copilot',
      'AI expense categorization',
      'AI vendor intelligence & duplicate detection',
      'AI document generation',
      'Natural language queries across modules',
      'Compliance calendar',
      'Compliance templates & tracking',
      'Submission tracking & activity logs',
      'Compliance reminders & escalations',
      'Document generation',
      'Document templates & branding profiles',
      'PDF / DOCX / HTML export',
      'Document version history',
      'AI tone, quality & content enhancement',
      'Basic dashboard',
      'Standard reports & CSV export',
      'Scheduled & saved reports',
      'Advanced analytics & forecasting',
      'Business health score & risk alerts',
      'AI-powered insights & summaries',
      'Email notifications',
      'In-app notifications',
      'Role-based permissions (RBAC)',
      'Audit logs & activity history',
    ]),
    business: new Set([
      'Create & send invoices',
      'PDF invoice generation',
      'Customer management',
      'Invoice status tracking',
      'Recurring invoices',
      'Unlimited invoices',
      'Manual payment recording',
      'Payment allocation to invoices',
      'Payment history & reports',
      'Accounts receivable dashboard',
      'Aging analysis',
      'Collections management',
      'Expense tracking',
      'Expense categories & suppliers',
      'Receipt & file attachments',
      'Expense export (CSV)',
      'Expense approval workflows',
      'Reimbursement management',
      'Budget tracking & alerts',
      'Recurring expenses & anomaly detection',
      'Basic AI assistant',
      'Workspace AI copilot',
      'AI expense categorization',
      'AI vendor intelligence & duplicate detection',
      'AI document generation',
      'AI compliance assistant',
      'AI action framework with governance',
      'Natural language queries across modules',
      'Compliance calendar',
      'Compliance templates & tracking',
      'Submission tracking & activity logs',
      'Compliance reminders & escalations',
      'Compliance intelligence & health scoring',
      'Risk detection & recommendations',
      'AI compliance actions & automation',
      'Document generation',
      'Document templates & branding profiles',
      'PDF / DOCX / HTML export',
      'Document version history',
      'AI tone, quality & content enhancement',
      'Basic dashboard',
      'Standard reports & CSV export',
      'Scheduled & saved reports',
      'Advanced analytics & forecasting',
      'Business health score & risk alerts',
      'AI-powered insights & summaries',
      'Email notifications',
      'In-app notifications',
      'SMS notifications',
      'Role-based permissions (RBAC)',
      'Audit logs & activity history',
      'Priority support',
      'API access & integrations',
      'Custom branding & white-label',
    ]),
  };

  const buildFeatures = (planCode) =>
    MASTER_FEATURES.map((f) => ({ ...f, included: PLAN_INCLUSIONS[planCode].has(f.label) }));

  const planData = [
    {
      code: 'free',
      name: 'Free',
      description: 'Get started with essential invoicing tools for solo operators and small teams.',
      monthlyPriceUsd: 0,
      yearlyPriceUsd: 0,
      displayOrder: 0,
      isRecommended: false,
      isPublic: true,
      includedUsers: 1,
      maxUsers: 1,
      maxMonthlyInvoices: 10,
      maxMonthlyAiRequests: 5,
      maxStorageMb: 100,
      hasExpenses: false,
      hasAiCategorization: false,
      hasAdvancedCompliance: false,
      trialDays: 0,
      features: buildFeatures('free'),
      isActive: true,
    },
    {
      code: 'starter',
      name: 'Starter',
      description: 'Everything you need to run a growing small business efficiently.',
      monthlyPriceUsd: 19,
      yearlyPriceUsd: 190,
      displayOrder: 1,
      isRecommended: false,
      isPublic: true,
      includedUsers: 3,
      maxUsers: 5,
      maxMonthlyInvoices: 50,
      maxMonthlyAiRequests: 50,
      maxStorageMb: 1024,
      hasExpenses: true,
      hasAiCategorization: false,
      hasAdvancedCompliance: false,
      trialDays: 14,
      features: buildFeatures('starter'),
      isActive: true,
    },
    {
      code: 'professional',
      name: 'Professional',
      description: 'AI-powered operations for ambitious teams ready to scale.',
      monthlyPriceUsd: 49,
      yearlyPriceUsd: 490,
      displayOrder: 2,
      isRecommended: true,
      isPublic: true,
      includedUsers: 5,
      maxUsers: 10,
      maxMonthlyInvoices: 200,
      maxMonthlyAiRequests: 200,
      maxStorageMb: 5120,
      hasExpenses: true,
      hasAiCategorization: true,
      hasAdvancedCompliance: false,
      trialDays: 14,
      features: buildFeatures('professional'),
      isActive: true,
    },
    {
      code: 'business',
      name: 'Business',
      description: 'Full-scale platform for established businesses with advanced AI and compliance needs.',
      monthlyPriceUsd: 99,
      yearlyPriceUsd: 990,
      displayOrder: 3,
      isRecommended: false,
      isPublic: true,
      includedUsers: 10,
      maxUsers: 25,
      maxMonthlyInvoices: null,
      maxMonthlyAiRequests: null,
      maxStorageMb: 20480,
      hasExpenses: true,
      hasAiCategorization: true,
      hasAdvancedCompliance: true,
      trialDays: 14,
      features: buildFeatures('business'),
      isActive: true,
    },
  ];

  for (const plan of planData) {
    await prisma.plan.upsert({
      where: { code: plan.code },
      update: plan,
      create: plan,
    });
  }
  console.log('Plans seeded: Free, Starter, Professional, Business');

  await seedCompliance(prisma);

  console.log('Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
