// Default detection rules — seeded globally (workspaceId = null)
const DEFAULT_RULES = [
  {
    ruleName: 'Privilege Escalation',
    category: 'Authorization',
    eventType: 'Members.RoleChanged',
    threshold: 1,
    windowMins: 60,
    riskScore: 25,
    severity: 'high',
    description: 'A workspace member role was changed to admin or owner.',
    recommendedAction: 'Verify the role change was authorized by a legitimate administrator.',
  },
  {
    ruleName: 'Member Removed',
    category: 'Authorization',
    eventType: 'Members.Removed',
    threshold: 1,
    windowMins: 60,
    riskScore: 15,
    severity: 'medium',
    description: 'A workspace member was removed.',
    recommendedAction: 'Confirm the removal was intentional and authorized.',
  },
  {
    ruleName: 'Mass Invoice Deletion',
    category: 'Financial Activity',
    eventType: 'Invoices.Deleted',
    threshold: 5,
    windowMins: 60,
    riskScore: 30,
    severity: 'high',
    description: 'Multiple invoices were deleted within a short time window.',
    recommendedAction: 'Review deleted invoices immediately. Check for unauthorized bulk deletions.',
  },
  {
    ruleName: 'Mass Customer Deletion',
    category: 'Data Modification',
    eventType: 'Customers.Deleted',
    threshold: 3,
    windowMins: 60,
    riskScore: 25,
    severity: 'high',
    description: 'Multiple customers were deleted within a short time window.',
    recommendedAction: 'Verify customer deletions were intentional and authorized.',
  },
  {
    ruleName: 'Bulk File Deletions',
    category: 'Data Access',
    eventType: 'Files.Deleted',
    threshold: 5,
    windowMins: 30,
    riskScore: 25,
    severity: 'high',
    description: 'Bulk file deletions detected — possible data loss or exfiltration.',
    recommendedAction: 'Review deleted files immediately and check for data loss.',
  },
  {
    ruleName: 'Payment Deletion',
    category: 'Financial Activity',
    eventType: 'Payments.Deleted',
    threshold: 3,
    windowMins: 60,
    riskScore: 35,
    severity: 'critical',
    description: 'Multiple payment records were deleted — possible financial fraud.',
    recommendedAction: 'Investigate payment deletions immediately. Review financial integrity.',
  },
  {
    ruleName: 'Subscription Cancelled',
    category: 'Administrative Activity',
    eventType: 'Billing.SubscriptionCancelled',
    threshold: 1,
    windowMins: 1440,
    riskScore: 20,
    severity: 'high',
    description: 'Workspace subscription was cancelled.',
    recommendedAction: 'Verify the cancellation was authorized. Contact owner if unexpected.',
  },
  {
    ruleName: 'Workspace Settings Changed',
    category: 'Configuration Changes',
    eventType: 'System.SettingsUpdated',
    threshold: 1,
    windowMins: 60,
    riskScore: 10,
    severity: 'medium',
    description: 'Workspace configuration settings were modified.',
    recommendedAction: 'Review the settings change to ensure it was expected and authorized.',
  },
  {
    ruleName: 'Compliance Task Overdue',
    category: 'Compliance Activity',
    eventType: 'Compliance.TaskOverdue',
    threshold: 1,
    windowMins: 1440,
    riskScore: 10,
    severity: 'medium',
    description: 'A compliance task has passed its due date without completion.',
    recommendedAction: 'Address overdue compliance tasks to avoid regulatory penalties.',
  },
  {
    ruleName: 'Mass Expense Approval',
    category: 'Financial Activity',
    eventType: 'Expenses.Approved',
    threshold: 10,
    windowMins: 30,
    riskScore: 20,
    severity: 'medium',
    description: 'Unusually high number of expenses approved in a short window.',
    recommendedAction: 'Verify bulk expense approvals were reviewed properly.',
  },
  {
    ruleName: 'Invoice Voided',
    category: 'Financial Activity',
    eventType: 'Invoices.Voided',
    threshold: 3,
    windowMins: 60,
    riskScore: 20,
    severity: 'medium',
    description: 'Multiple invoices voided in a short window.',
    recommendedAction: 'Review voided invoices to confirm they were authorized.',
  },
  {
    ruleName: 'New Member Joined',
    category: 'Authorization',
    eventType: 'Members.Joined',
    threshold: 1,
    windowMins: 60,
    riskScore: 5,
    severity: 'info',
    description: 'A new member joined the workspace.',
    recommendedAction: 'Confirm the new member was expected and has appropriate role assignment.',
  },
];

module.exports = { DEFAULT_RULES };
